name: Bygg og publiser docker-image for main

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - .github/workflows/**

jobs:
  build-and-publish-on-main:
    runs-on: ubuntu-latest
    steps:

      - name: Sjekk ut koden
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.13

      - name: Finn cache-variabler
        uses: navikt/pb-common-gh-actions/cache-prep@v2

      - name: Sett opp cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.CACHE_PATHS }}
          key: ${{ runner.os }}${{ env.CACHE_KEY_NAMESPACE }}${{ hashFiles(env.CACHE_KEY_HASHED_PATH) }}

      - name: Bygg prosjekt og kjør tester
        uses: navikt/pb-common-gh-actions/build@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bygg, tag og push Docker image
        uses: navikt/pb-common-gh-actions/docker-publish@v2
        with:
          TAG_LATEST: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag release i git-repo-et
        run: |
          TAG="$(git log -1 --pretty='%ad' --date=format:'%Y%m%d%H%M%S')-$(git log -1 --pretty='%h')"
          git config user.name "Team Personbruker CI"
          git config user.email "personbruker@nav.no"
          git tag $TAG
          git push origin $TAG
